SystemOrganization addCategory: #'FAST-Model'!
SystemOrganization addCategory: #'FAST-Importer'!
SystemOrganization addCategory: #'FAST-Test-Importer'!
SystemOrganization addCategory: #'FAST-TestResources'!
SystemOrganization addCategory: #'FAST-Visualization'!
SystemOrganization addCategory: #'FAST-Scope'!
SystemOrganization addCategory: #'FAST-Model-Extention'!
SystemOrganization addCategory: #'FAST-Resolution'!
